CREATE TABLE `PLACE`
(
    `ID`                BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `COMPANY_ID`        BIGINT UNSIGNED NOT NULL,
    `PLACE_NAME`        VARCHAR(30) NOT NULL,
    `PLACE_DESCRIPTION` VARCHAR(50) NOT NULL,
    `PLACE_OPENDAYS`    VARCHAR(50) NOT NULL,
    `PLACE_START`       TIME        NOT NULL,
    `PLACE_END`         TIME        NOT NULL,
    `PLACE_ADDINFO`     VARCHAR(50) NOT NULL,
    `ADDRESS_ID`        BIGINT UNSIGNED NOT NULL
);