CREATE TABLE `PLACE`
(
    `ID`                BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `COMPANY_ID`        BIGINT UNSIGNED NOT NULL,
    `PLACE_NAME`        VARCHAR(30) NOT NULL,
    `PLACE_DESCRIPTION` VARCHAR(50) NOT NULL,
    `PLACE_OPENDAYS`    VARCHAR(50) NOT NULL,
    `PLACE_START`       TIME        NOT NULL,
    `PLACE_END`         TIME        NOT NULL,
    `PLACE_ADDINFO`     VARCHAR(50) NOT NULL,
    `ADDRESS_ID`        BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `COMPANY`
(
    `ID`              BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `COMPANY_LOGINID` VARCHAR(15) NOT NULL,
    `COMPANY_PW`      VARCHAR(15) NOT NULL,
    `COMPANY_NAME`    VARCHAR(30) NOT NULL,
    `COMPANY_TEL`     VARCHAR(22) NOT NULL,
    `COMPANY_REGNUM`  VARCHAR(12) NOT NULL,
    `COMPANY_REPNAME` VARCHAR(20) NOT NULL,
    `ADDRESS_ID`      BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `LOCATION`
(
    `ID`         BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `ADDRESS`    VARCHAR(100) NOT NULL,
    `POSTALCODE` VARCHAR(5)   NOT NULL
);