CREATE TABLE `PLACE`
(
    `ID`                BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `COMPANY_ID`        BIGINT UNSIGNED NOT NULL,
    `PLACE_NAME`        VARCHAR(30) NOT NULL,
    `PLACE_DESCRIPTION` VARCHAR(50) NOT NULL,
    `PLACE_OPENDAYS`    VARCHAR(50) NOT NULL,
    `PLACE_START`       TIME        NOT NULL,
    `PLACE_END`         TIME        NOT NULL,
    `PLACE_ADDINFO`     VARCHAR(50) NOT NULL,
    `ADDRESS_ID`        BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `COMPANY`
(
    `ID`              BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `COMPANY_LOGINID` VARCHAR(15)  NOT NULL,
    `COMPANY_PW`      VARCHAR(100) NOT NULL,
    `COMPANY_NAME`    VARCHAR(30)  NOT NULL,
    `COMPANY_TEL`     VARCHAR(22)  NOT NULL,
    `COMPANY_REGNUM`  VARCHAR(12)  NOT NULL,
    `COMPANY_REPNAME` VARCHAR(20)  NOT NULL,
    `ADDRESS_ID`      BIGINT UNSIGNED NOT NULL
);

CREATE TABLE `LOCATION`
(
    `ID`         BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `ADDRESS`    VARCHAR(100) NOT NULL,
    `POSTALCODE` VARCHAR(5)   NOT NULL
);

CREATE TABLE `ROOM`
(
    `ID`           BIGINT UNSIGNED primary key NOT NULL auto_increment,
    `ROOM_KIND_ID` BIGINT UNSIGNED NOT NULL,
    `PLACE_ID`     BIGINT UNSIGNED NOT NULL,
    `COMPANY_ID`   BIGINT UNSIGNED NOT NULL,
    `TOTAL_NUM`    INT(3) UNSIGNED NOT NULL,
    `ROOM_STATE`   BOOLEAN NOT NULL
);

CREATE TABLE `ROOM_KIND`
(
    `ID`        BIGINT UNSIGNED primary key NOT NULL,
    `ROOM_TYPE` ENUM ('DESK', 'MEETINGROOM4', 'MEETINGROOM6', 'MEETINGROOM10', 'MEETINGROOM20', 'OFFICE20', 'OFFICE40', 'OFFICE70', 'OFFICE100') NOT NULL,
    `PRICE`     ENUM ('10000', '20000', '30000', '50000', '100000', '200000', '300000', '500000') NOT NULL
);

INSERT INTO `ROOM_KIND`
values (1, 'DESK', '10000');

INSERT INTO `ROOM_KIND`
values (2, 'MEETINGROOM4', '20000');

INSERT INTO `ROOM_KIND`
values (3, 'MEETINGROOM6', '30000');

INSERT INTO `ROOM_KIND`
values (4, 'MEETINGROOM10', '50000');

INSERT INTO `ROOM_KIND`
values (5, 'MEETINGROOM20', '100000');

INSERT INTO `ROOM_KIND`
values (6, 'OFFICE20', '100000');

INSERT INTO `ROOM_KIND`
values (7, 'OFFICE40', '200000');

INSERT INTO `ROOM_KIND`
values (8, 'OFFICE70', '300000');

INSERT INTO `ROOM_KIND`
values (9, 'OFFICE100', '500000');


CREATE TABLE `USER`
(
    `ID`          BIGINT UNSIGNED primary key AUTO_INCREMENT NOT NULL,
    `MILEAGE_ID`  BIGINT UNSIGNED NOT NULL,
    `USER_MAIL`   VARCHAR(32)  NOT NULL,
    `USER_PW`     VARCHAR(100) NOT NULL,
    `USER_NAME`   VARCHAR(20)  NOT NULL,
    `USER_TEL`    VARCHAR(22)  NOT NULL,
    `USER_JOB`    VARCHAR(20)  NOT NULL,
    `prefer_type` VARCHAR(50)  NOT NULL
);

CREATE TABLE `MILEAGE`
(
    `ID`    BIGINT UNSIGNED primary key AUTO_INCREMENT NOT NULL,
    `POINT` INT(11) NOT NULL
);

create table RESERVATION
(
    ID            BIGINT UNSIGNED AUTO_INCREMENT primary key,
    PLACE_ID      BIGINT UNSIGNED not null,
    USER_ID       BIGINT UNSIGNED not null,
    ROOM_ID       BIGINT UNSIGNED not null,
    ROOM_KIND_ID  BIGINT UNSIGNED not null,
    RES_STARTDATE DATE NOT NULL,
    RES_STARTTIME TIME NOT NULL,
    RES_ENDDATE   DATE NOT NULL,
    RES_ENDTIME   TIME NOT NULL
);

INSERT INTO RESERVATION (ID, PLACE_ID, USER_ID, ROOM_ID, ROOM_KIND_ID, RES_STARTDATE, RES_STARTTIME,
                         RES_ENDDATE, RES_ENDTIME)
VALUES (15, 1, 1, 1, 1, '2022-01-01', '11:00:00', '2022-01-01', '14:00:00');
