CREATE TABLE `COMPANY`
(
    `ID`              BIGINT UNSIGNED NOT NULL,
    `COMPANY_LOGINID` VARCHAR(15) NOT NULL,
    `COMPANY_PW`      VARCHAR(15) NOT NULL,
    `COMPANY_NAME`    VARCHAR(30) NOT NULL,
    `COMPANY_TEL`     VARCHAR(22) NOT NULL,
    `COMPANY_REGNUM`  VARCHAR(12) NOT NULL,
    `COMPANY_REPNAME` VARCHAR(20) NOT NULL,
    `ADDRESS_ID`      BIGINT UNSIGNED NOT NULL
);